<!doctype html>
<html>
<head>
<title>Trend Micro SVG Icons</title>
<meta charset="utf-8">
<meta name="description" content="SVG Icons Generated By Trend Micro">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="demo-files/icon-svg-demo.css">
<link rel="stylesheet" href="icon-svg.css">
</head>
<body>
_symbol
<header class="bgc1 clearfix">
    <div class="mhl">
        <p>SVG Icons - Generated by <a href="http://style-portal.tw.trendnet.org">Trend Micro Style Portal</a></p>
    </div>
</header>
_iconSets
<script defer src="svgxuse.js"></script>
</body>
</html>
