<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Trend Micro Icon Font</title>
    <meta name="description" content="An Icon Font Generated By Trend Micro">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="demo-files/icon-font-demo.css">
    <link rel="stylesheet" href="icon-font.css"></head>
<body>
    <div class="wrapper">
        <div class="bgc1 clearfix">
            <h1 class="mhmm mvm"><span class="fgc1">Font Name:</span> _fontName <small class="fgc1">(Glyphs:&nbsp;_glyphsCount)</small></h1>
        </div>
        <div class="clearfix mhl ptl">
            <h1 class="mvm mtn fgc1">Grid Size: _gridSize</h1>
            <!--Icons repeater-->
        </div>

        <!--[if gt IE 8]><!-->
        <div class="test-drive mhl clearfix mbl">
            <h1>Font Test Drive</h1>
            <label>
                Font Size: <input id="fontSize" type="number" class="textbox0 mbm"
                min="8" value="48" />
                px
            </label>
            <input id="testText" type="text" class="phl size1of1 mvl"
            placeholder="Type some text to test..." value=""/>
            <div id="testDrive" class="">&nbsp;
            </div>
        </div>
        <!--<![endif]-->
        <div class="footer bgc1 clearfix">
            <p class="mhl">Generated by <a href="http://style-portal.tw.trendnet.org" target="_blank">Trend Micro Style Portal</a></p>
        </div>
    </div>
    <script src="demo-files/icon-font-demo.js"></script>
    <!--Script placeholder-->
</body>
</html>
