<!doctype html>
<html>
<head>
<title>Trend Micro SVG Icons</title>
<meta charset="utf-8">
<meta name="description" content="SVG Icons Generated By Trend Micro">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="demo-files/icon-svg-demo.css">
<link rel="stylesheet" href="icon-svg.css">
</head>
<body>
_symbol
<div class="wrapper">
    <div class="bgc1 clearfix">
        <h1 class="mvm">TM Icon SVG Preview</h1>
        <p>
            For detailed guidelines, please go to the <a href="http://style-portal.tw.trendnet.org/#/styles/minimalism/latest/f558e7db-82df-426a-93a6-c0ad072bb894">Trend Micro Style Portal</a>.<br/>
            Date generated: _generatedDate
        </p>
    </div>
    _iconSets
    <div class="footer bgc1 clearfix">
        <p>Generated by <a href="http://style-portal.tw.trendnet.org" target="_blank">Trend Micro Style Portal</a></p>
    </div>
</div>
<script defer src="svgxuse.js"></script>
</body>
</html>
