<!-- Generated by Figma TMIconBuddy -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="_viewBox" height="_viewBox" viewBox="0 0 _viewBox _viewBox">
  <title>_title</title>
  <!--paths-->
</svg>