<!-- Generated by Trend Micro Style Portal -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 _viewBox _viewBox">
  <title>_title</title>
  <!--paths-->
</svg>