name: Build TMIcons

on:
  push:
    branches:
      - dev

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js 20
      uses: actions/setup-node@v3

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download font files
      run: |
        ls
        css_url="https://i.icomoon.io/public/a8317e20c1/TMIcons/style.css"
        css_file="style.css"
        dist_dir="dist/fonts"

        curl -o $css_file $css_url
        font_urls=$(grep -oP 'url\(\K[^)]+' style.css | sort -u)

        # curl -o "dist/fonts/TMicon.eot" "https://i.icomoon.io/public/a8317e20c1/TMIcons/TMicon.eot?73rtx5#iefix"
        for url in $font_urls; do
          echo "$url"
          clean_url=$(echo $url | sed 's/[?#].*//')
          filename=$(basename "$clean_url")
          path="$dist_dir/$filename"
          echo "$path"
          curl -o $path "https://i.icomoon.io/public/a8317e20c1/TMIcons/TMicon.eot?73rtx5#iefix"
        done

    # rm $css_file

    # echo "Font files downloaded successfully."

    # - name: Configure Git
    #   run: |
    #     git config --global user.name 'HIE UX Service'
    #     git config --global user.email 'hie_ux_service@trendmicro.com'

    # - name: Add changes
    #   run: git add test.txt

    # - name: Commit changes
    #   run: git commit -m "Add test.txt with dynamic content"

    # - name: Push changes
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #   run: git push origin dev